Models/ErrorViewModel.cs
namespace testando.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using testando.Models;

namespace testando.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ParceriasController.cs
using Microsoft.AspNetCore.Mvc;

public class ParceriasController:Controller{
    
    public IActionResult Index(){
        return View();
    }

    public IActionResult Oracle(){
        return View();
    }

    public IActionResult Cisco(){
        return View();
    }

    public IActionResult Huawei(){
        return View ();
    }

    public IActionResult Google(){
        return View();
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class=>Apresentando as parcerias do SENAI</h1>
</div>

Views/Parcerias/Cisco.cshtml
<h1>Bem vindo à Cisco System</h1>

<p>A Cisco Systems, Inc. foi fundada em 10 de dezembro de 1984, por Leonard Bosack e Sandra Lerner
    ambos cientistas de computação da Stanford University, na época. Hoje, a empresa é sediada em San José, na Califórnia
    tendo como principal ramo de atuação a fabricação e distribuição de soluções em equipamentos de rede.</p>

Views/Parcerias/Google.cshtml
<h1>Bem vindo à Google</h1>

<p>O Google é uma empresa fundada em 4 de setembro de 1998 em Menlo Park, na Califórnia
    costa oeste dos Estados Unidos. Os criadores são Larry Page e Sergey Brin, dois estudantes do curso de doutorado da Universidade de Stanford.</p>

Views/Parcerias/Huawei.cshtml
<h1>Bem vindo à Huawei</h1>

<p> A Huawei foi fundada em 1987 por Ren Zhengfei e é uma empresa proprietária.
    Suas atividades principais são pesquisa e desenvolvimento, a produção e o marketing de equipamentos de telecomunicações
    e o fornecimento de serviços personalizados de rede a operadoras de telecomunicações dentro e fora da China.</p>

Views/Parcerias/Index.cshtml
<h1>Bem vindo à Microsoft</h1>

<p>A Microsoft é uma empresa de tecnologia fundada por Bill Gates e Paul Allen, em 1975, nos Estados Unidos.
    Com sede em Redmond (Washington), a companhia atua no suporte e desenvolvimento de softwares
    dispositivos e serviços relacionados à computação pessoal, produtividade e soluções em nuvem.</p>

Views/Parcerias/Oracle.cshtml
<h1>Bem vindo à Oracle</h1>

<p>A Oracle foi fundada em agosto de 1977, inicialmente foi chamada de Software Development Labs (SDL)
    uma empresa de consultoria que contava com Bob Miner (presidente), Ed Oates e Bruce Scott (engenheiros de software)
    no seu primeiro projeto.</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - testando</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/testando.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">testando</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parcerias" asp-action="Index">Microsoft</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parcerias" asp-action="Oracle">Oracle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parcerias" asp-action="Cisco">Cisco</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parcerias" asp-action="Huawei">Huawei</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parcerias" asp-action="Google">Google</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - testando - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>